### ISSUE TITLE
I can't get my devices

### ISSUE THREAD

**Issue by gdetra** [vidstige/jadb#50] opened 2017-01-28 10:30 UTC
Can you tell me how can i recognize my device with adb enabled?
i have tried getAnyDevice method but nothing to do.. help me please!!

**Comment by SKART1** [comment] 2017-01-28 11:44
Can you provide more information about regime in which adb is started?

Does `adb devices` show anything?
Is it real device or emulator?
What OS are you using?

**Comment by gdetra** [comment] 2017-01-28 11:49
i'm under Windows. When i run `adb devices` command ,it returns me my device with serial code.
mine is real device. 
this is the java code that i'm using:
`JadbConnection jadb = new JadbConnection();
		JadbDevice device = jadb.getAnyDevice();
		System.out.println(device.getSerial());
		System.out.println(device.getState());`

**Comment by SKART1** [comment] 2017-01-28 12:12
Can you try `jadb.getDevices();` istead?

What are the error? NullPointerException - or just empty output

**Comment by gdetra** [comment] 2017-01-28 12:24
null
Exception in thread "main" java.net.ConnectException: Connection refused: connect
	at java.net.DualStackPlainSocketImpl.connect0(Native Method)
	at java.net.DualStackPlainSocketImpl.socketConnect(Unknown Source)
	at java.net.AbstractPlainSocketImpl.doConnect(Unknown Source)
	at java.net.AbstractPlainSocketImpl.connectToAddress(Unknown Source)
	at java.net.AbstractPlainSocketImpl.connect(Unknown Source)
	at java.net.PlainSocketImpl.connect(Unknown Source)
	at java.net.SocksSocketImpl.connect(Unknown Source)
	at java.net.Socket.connect(Unknown Source)
	at java.net.Socket.connect(Unknown Source)
	at java.net.Socket.<init>(Unknown Source)
	at java.net.Socket.<init>(Unknown Source)
	at se.vidstige.jadb.JadbConnection.createTransport(JadbConnection.java:25)
	at se.vidstige.jadb.JadbDevice.getTransport(JadbDevice.java:28)
	at se.vidstige.jadb.JadbDevice.getState(JadbDevice.java:44)
	at DeviceClass.main(DeviceClass.java:19)

**Comment by gdetra** [comment] 2017-01-28 12:27
after `adb start-server` the exception is 
`
null
Exception in thread "main" se.vidstige.jadb.JadbException: command failed: closed
	at se.vidstige.jadb.Transport.verifyResponse(Transport.java:39)
	at se.vidstige.jadb.JadbDevice.getState(JadbDevice.java:46)
	at DeviceClass.main(DeviceClass.java:19)
`

**Comment by gdetra** [comment] 2017-01-28 19:04
any solutions?

**Comment by gdetra** [comment] 2017-01-28 23:40
With getDevices() now i can get serial number, but for state i have the same exception

**Comment by SKART1** [comment] 2017-01-30 10:11
Sorry I do not have windows host to test

You may try to debug actual response to determine what is the error

**Comment by vidstige** [comment] 2017-01-30 14:56
Interesting. The `getAnyDevice` addresses devices in a different way if I recall correctly. What is your adb version?

**Comment by gdetra** [comment] 2017-01-30 22:46
1.0.32 (adb version)

**Comment by gdetra** [comment] 2017-02-02 18:25
@vidstige any solutions?

**Comment by vidstige** [comment] 2017-02-03 13:26
@gdetra Alright, I've looked into this. I could not reproduce your problem with adb version 1.0.31 on Windows. Some question to help me troubleshoot this. I ran the `RealDeviceTestCases.testListFilesTwice()` test method and it works as expected. It calls the `JadbConnection.getAnyDevice()` method.

* Are you using the maven package or do you have the source checked out. If you have the code checked out, can you please try to run the `RealDeviceTestCases` test suite?
* What's your exact OS version?
* What Android device(s) are you using to reproduce this?
* Could you please try with adb 1.0.32 (just in case there is some protocol change in that version)

Thanks for your patience.

**Comment by gdetra** [comment] 2017-02-04 12:00
i'm using maven package. I use Windows 10 anniverasy update (Surface pro 4). My phone is a Xiaomi mi5.
i haven't trying with another device. i'm trying with `testListFilesTwice()`

**Comment by gdetra** [comment] 2017-02-05 15:53
@vidstige even with adb version 1.0.31 i have the same exception. How can i use realDeviceTestCases?

**Comment by vidstige** [comment] 2017-02-06 12:33
Hmm, that worked for me. The device _should_ not matter in this case. Very strange indeed. It works on my Windows machine as I wrote before. Some more things you could try to help me get more information on this:

* Can you try with an emulator? How does that work?
* Check the adb daemon log (somewhere on the device) for any errors during this exception.

**Comment by gdetra** [comment] 2017-02-09 16:35
i have tried with an emulator and the result is the same. Can you tell me , @vidstige , how can i get this log? i have tried in tmp folder but i haven't found nothing. Help me please!

**Comment by vidstige** [comment] 2017-02-09 19:58
What version of _jadb_ are you using? Can you try checking out latest master and see how it works there? Latest master works for me when I tested. As a workaround - Can't you just use `jadb.getDevices()`? What do you want to do?

* The adb daemon log should be inside the regular logcat. E.g. try to run `getAnyDevice` and watch logcat output, note any errors and paste here.
* Also try to run with latest master _jadb_ as I have tested that and it works.

**Comment by SKART1** [comment] 2017-02-13 14:15
May be it is some firewall? Try to switch it at least for some time

May you try different PC/wire/phone?

**Comment by gdetra** [comment] 2017-02-20 09:14
@SKART1 i have tried but nothing to do. @vidstige i cannot find adb daemon log; if it is logcat i don't know how to show it.

**Comment by gdetra** [comment] 2017-02-20 09:36
@vidstige i have this version "number" because v1.1 give me cannot find error
`94ebf38`
I got it from  [here]((https://github.com/vidstige/jadb/issues/14))

**Comment by vidstige** [comment] 2017-02-20 13:12
Alright, so you cannot use the latest version in JitPack? So what I mean is, can you please try to `git clone` this repository and run the test from there?

**Comment by SKART1** [comment] 2017-02-21 18:54
@vidstige 
Latest version is v1.0.1 - see [jitpack](https://jitpack.io/#vidstige/jadb/v1.0.1)

As for your problem - may be java programs run`s isn some kind of sandbox in latest windows OS?
You may try to dump traffic between:

*  adb client + adb server 
*  jadb + adb server 

to compare them. You can do it with [wireshark](https://www.wireshark.org) 

But I am sure this should not be so difficult =(

**Comment by vidstige** [comment] 2017-04-19 16:35
Closing this for now.

**Closed by vidstige** 2017-04-19 16:35 UTC
