### ISSUE TITLE
java.io.EOFException: null in JadbDevice.pull and SyncTransport.readChunk() when reading file from a device

### ISSUE THREAD

**Issue by aaronmagi** [vidstige/jadb#55] opened 2017-02-10 21:45 UTC
Hi,

We ran into an issue today while using JADB.  The phone took over 40 minutes to respond while trying to read the pull to retrieve around a 15mb file.    It looks to fail when trying to readChunk() in the SyncTransport.

        java.io.EOFException: null
      at java.io.DataInputStream.readFully(DataInputStream.java:197)
      at se.vidstige.jadb.SyncTransport.readChunk(SyncTransport.java:83)
      at se.vidstige.jadb.SyncTransport.readChunksTo(SyncTransport.java:101)
      at se.vidstige.jadb.JadbDevice.pull(JadbDevice.java:126)
      at se.vidstige.jadb.JadbDevice.pull(JadbDevice.java:131)
      at com.test.executors.VideoCaptureExecutor.copyFile(VideoCaptureExecutor.java:130)
      at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
      at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:720)
      at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
      at org.springframework.aop.interceptor.AsyncExecutionInterceptor$1.call(AsyncExecutionInterceptor.java:115)
      at java.util.concurrent.FutureTask.run(FutureTask.java:266)
      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
      at java.lang.Thread.run(Thread.java:745)
    14:57:13.014 [device-Runner-18] ERROR c.m.m.a.e.VideoCaptureExecutor - Device samsung SAMSUNG-SM-G920A 351807070178804: Error trying to process videoExecutor
    se.vidstige.jadb.JadbException: command failed: device '1215fc9b507f3504' not found
      at se.vidstige.jadb.Transport.verifyResponse(Transport.java:63)
      at se.vidstige.jadb.JadbDevice.getTransport(JadbDevice.java:32)
      at se.vidstige.jadb.JadbDevice.executeShell(JadbDevice.java:53)
      at se.vidstige.jadb.JadbDevice.executeShell(JadbDevice.java:49)
      at com.test.executors.VideoCaptureExecutor.copyFile(VideoCaptureExecutor.java:137)
      at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
      at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:720)
      at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
      at org.springframework.aop.interceptor.AsyncExecutionInterceptor$1.call(AsyncExecutionInterceptor.java:115)
      at java.util.concurrent.FutureTask.run(FutureTask.java:266)
      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
      at java.lang.Thread.run(Thread.java:745)

We wanted to know if you have ran into any issues with this or if you would be able to take a look?

Thank you

**Comment by vidstige** [comment] 2017-02-12 07:33
Thanks for reporting this issue
* Can you reproduce this? E.g. does it happen every time you try?
* Does it happen with all files? Can you try e.g. with a very small file.
* If it only happens with this file, can you share it somehow then I can look into this.

**Comment by SKART1** [comment] 2017-02-12 14:25
Are you sure you not executing multiple commands on device concurrently?

**Comment by aaronmagi** [comment] 2017-03-17 17:15
@SKART1 yes we are.

Is that a issue?

I just noticed again today some very interesting behaviour where it looks like the device can not be found when another thread is reading a part of a file and a new thread tries to read from the device as well.

Aaron

**Comment by vidstige** [comment] 2017-03-17 21:11
Can you post a minimal example that exhibit this behaviour? I tried to download a 15mb file, but it worked fine.

**Comment by SKART1** [comment] 2017-03-20 09:21
@aaronmagi looks like adb have problems with it (I think adb daemon which is on device, but it may be an adb server issue)

Firstly device should be always connected to only one adb server (not your case - just remind)
Secondly - we have faced problem with simultaneously executing test with (from shell, not jadb):

```
ADB_SHELL_INSTRUMENT =
            "adb shell am instrument -w \\\n" +
            "-r \\\n" +
            " %s" + " \\\n" +  // arguments
            " %s " + " \\\n"+  //class
            " %s/%s\n";
```
and reading logcat from device with:

```
adb logcat > 1.txt
```

When starting next test - adb client showed that device is offline

Finally - I think that it may be caused by not correctly closed connection, but need more debugging


**P.S.** As a workaround - not to use adb server simultaneously

**Comment by vidstige** [comment] 2017-03-20 10:04
Thanks for this @SKART1 . I'll close this issue for now, @aaronmagi if you would like to reopen this issue, could you please first try to reproduce without jadb as described above. If it is indeed a jadb issue, please add some steps to reproduce it.

**Closed by vidstige** 2017-03-20 10:04 UTC
